dataset: [ 'Hospital' ]

network: "segnetvit"

local_rank: 0
gpu: [ 0,1,2,5]

feature: "sfd2"
save_path: '/scratches/flyer_2/fx221/exp/pram'
landmark_path: "/scratches/flyer_2/fx221/publications/test_pram/Hospital/landmarks/sfd2-gml"
dataset_path: "/scratches/flyer_3/fx221/dataset"
config_path: 'configs/datasets'

image_dim: 3
feat_dim: 128
min_inliers: 32
max_inliers: 256
random_inliers: 1
max_keypoints: 512
ignore_index: -1
output_dim: 1024
output_dim_: 2048
jitter_params:
  brightness: 0.5
  contrast: 0.5
  saturation: 0.25
  hue: 0.15
  blur: 0

scale_params: [ 0.5, 1.0 ]
pre_load: false
train: true
inlier_th: 0.5
lr: 0.0001
min_lr: 0.00001
optimizer: "adam"
seg_loss: "cew"
seg_loss_nx: "cei"
cls_loss: "ce"
cls_loss_: "bce"
sc_loss: 'l1g'
ac_fn: "relu"
norm_fn: "bn"
workers: 8
layers: 15
log_intervals: 50
eval_n_epoch: 10

use_mid_feature: true
norm_desc: false
with_sc: false
with_cls: true
with_score: false
with_aug: true
with_dist: true

batch_size: 32
its_per_epoch: 1000
decay_rate: 0.999992
decay_iter: 50000
epochs: 500
do_eval: false

cluster_method_: 'kmeans'
cluster_method: 'birch'

weight_path: null
resume_path: null

eval: false
loc: false
#loc: true
online: false
#online: true
n_class: 129

eval_max_keypoints: 4096

localization:
  loc_scene_name: [ ]
  save_path: '/scratches/flyer_2/fx221/exp/localizer/loc_results'
  dataset: [ 'CUED' ]
  seg_k: 30
  threshold: 12
  min_kpts: 256
  min_matches: 16
  min_inliers: 32
  matching_method_: "mnn"
  matching_method_1: "spg"
  matching_method: "gm"
  save: false
  show: true
  show_time: 1
  max_vrf: 1
  with_original: true
  with_extra: false
  with_compress: true
  semantic_matching: True
  do_refinement: false
  refinement_method_: 'matching'
  refinement_method: 'projection'
  covisibility_frame: 20
  refinement_radius: 20
  refinement_nn_ratio: 0.9
  refinement_max_matches: 0

