dataset: [ 'T' ]

network: "segnet"
network_3: "gsegnet3"

local_rank: 0
gpu: [ 0,1,2,3 ]

feature: "spp"
save_path: '/scratches/flyer_2/fx221/exp/localizer'
segment_path: "/scratches/flyer_3/fx221/exp/localizer/superpoint-n4096-superglue"
dataset_path: "/scratches/flyer_3/fx221/dataset"
config_path: '/home/mifs/fx221/Research/Code/localizer/configs/datasets'

image_dim: 1
min_inliers: 32
max_inliers: 512
random_inliers: 1
max_keypoints: 1024
ignore_index: -1
output_dim: 1024
output_dim_: 2048
jitter_params:
  brightness: 0.5
  contrast: 0.5
  saturation: 0.25
  hue: 0.15
  blur: 0

scale_params: [ 0.5, 1.0 ]
pre_load: false
do_eval: true
train: true
inlier_th: 0.5
lr: 0.0001
min_lr: 0.00001
optimizer: "adam"
seg_loss: "cew"
seg_loss_nx: "cei"
cls_loss: "ce"
cls_loss_: "bce"
sc_loss: 'l1g'
ac_fn: "relu"
norm_fn: "bn"
workers: 8
layers: 15
log_intervals: 50
eval_n_epoch: 10

use_mid_feature: true
norm_desc: false
with_sc: false
with_cls: true
with_score: false
with_aug: true
with_dist: true

batch_size: 32
its_per_epoch: 1000
decay_rate: 0.999992
decay_iter: 80000
epochs: 200

cluster_method_: 'kmeans'
cluster_method: 'birch'

weight_path: null
resume_path: null

eval: false
loc: false

eval_max_keypoints: 4096

localization:
  loc_scene_name: [ ]
  save_path: '/scratches/flyer_2/fx221/exp/localizer/loc_results'
  dataset: [ 'S' ]
  seg_k: 20
  threshold: 8
  min_kpts: 256
  min_matches: 16
  min_inliers: 64
  matching_method_: "mnn"
  matching_method: "spg"
  save: false
  show: true
  show_time: 3
  do_refinement: true
  with_original: true
  max_vrf: 1
  with_extra: false
  with_nms: false
  with_compress: true
  covisibility_frame: 20
  observation_threshold: 3