dataset: 'DarwinRGB'
scenes: [ 'darwin' ]


darwin:
  n_cluster: 128
  n_cluster_: 256
  cluster_mode: 'xy'
  cluster_method_: 'kmeans'
  cluster_method: 'birch'

  training_sample_ratio: 1
  eval_sample_ratio: 5
  gt_pose_path: 'queries_poses_aligned.txt'
  query_path: 'queries_with_intrinsics_aligned.txt'

  gt_pose_path_3: 'queries_poses_realme.txt'
  query_path_3: 'queries_with_intrinsics_realme.txt'
  image_path_prefix: 'db'
